# Generated by Django 5.2 on 2025-10-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
